Repository milieuinfo/webcomponent-vl-ui-core, pull requests merged in 2019-11, with the labels that each got.

#23 README.md aangepast
  README.md
Labels: task

#25 Update README.md
  README.md
  core-style.css
  core-style.css.map
  package-lock.json
  package.json
Labels: maintenance

#26 Voeg vl-element als component voor e2e toe
  package.json
  test/e2e/components/vl-element.js
Labels: task

#29 Update core via util
  test/docker-compose.yml
Labels: bugfix

#30 Update core via util
  bamboo-specs/bamboo.yml
  docker-compose.yml
  package.json
  test/docker-compose.yml
  test/wct.docker.conf.json
Labels: bugfix

#32 UIG-271 Nieuwe test setup
  index.js
  package-lock.json
  package.json
  test/e2e/config.js
  test/e2e/pages/page.js
  test/e2e/test.js
Labels: chore

#33 Voeg baseUrl toe aan config. Wanneer de E2E testen in een container gedraaid worden, dan is localhost niet beschikbaar en moet de naam van de container gebruikt worden. In dit geval 'tests'
  test/e2e/config.js
Labels: bugfix

#34 Voeg functie toe om de shadowRoot van een vlElement aan te spreken
  test/e2e/components/vl-element.js
Labels: chore
