Repository milieuinfo/webcomponent-vl-ui-core, pull requests merged in 2020-03, with the labels that each got.

#59 Introductie E2E page object util functies isInViewport en scrollToTop
  test/e2e/components/vl-element.js
Labels: chore

#60 Wijziging implementatie probleem E2E page object isInViewport functie
  test/e2e/components/vl-element.js
Labels: chore

#61 Ondersteuning voor data-vl prefix bij attributen
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/task.md
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
  src/vl-core.js
  test/docker-compose.yml
  test/unit/vl-core.test.html
  test/unit/vl-element.js
  test/unit/vl-native-element.js
  wct.docker.conf.json
  wct.local.conf.json
Labels: enhancement

#63 Oplossen problemen met styling in Chrome mobile en Safari voor NativeVlElements
  src/vl-core.js
Labels: bug

#64 Ondersteuning voor verouderde attribuut changed callback functies met prefix
  src/vl-core.js
  test/unit/vl-core.test.html
  test/unit/vl-element.js
  test/unit/vl-native-element.js
Labels: bug

#65 Fixed probleem met changed attribuut callback functie getter
  package-lock.json
  package.json
  src/vl-core.js
Labels: bug

#68 Introductie E2E get parent functie
  test/e2e/components/vl-element.js
Labels: enhancement
