Repository milieuinfo/webcomponent-vl-ui-core, pull requests merged in 2020-06, with the labels that each got.

#78 Import sinon uit node_modules voor de unit testen
  package-lock.json
  test/unit/vl-core.test.html
Labels: bugfix

#80 Tekst trimmen bij e2e testen
  test/e2e/components/vl-element.js
Labels: enhancement

#84 Geen header/footer tonen tijdens e2e testen
  test/e2e/pages/page.js
Labels: chore

#85 Introductie nieuw Vlaanderen icon font
  package-lock.json
  package.json
  src/style.css
Labels: bug

#87 Duplicatie scripts wegwerken
  package-lock.json
  test/e2e/config.js
Labels: chore
